-- ============================================
-- 프리다이빙 교육관리 시스템 v2 DB 마이그레이션
-- 포함 테이블: debriefings, course_progress, skill_completions, certificates
-- ============================================

-- 1. debriefings 테이블 (상세 디브리핑)
-- reservations 테이블과 1:1 관계 (하나의 예약에 하나의 디브리핑)
CREATE TABLE IF NOT EXISTS public.debriefings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id UUID NOT NULL REFERENCES public.reservations(id) ON DELETE CASCADE,
    instructor_id UUID NOT NULL REFERENCES public.profiles(id),
    performance TEXT, -- 수행 평가
    improvement TEXT, -- 개선 포인트
    strengths TEXT,   -- 잘한 점
    next_goal TEXT,   -- 다음 목표
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(reservation_id)
);

-- RLS 활성화
ALTER TABLE public.debriefings ENABLE ROW LEVEL SECURITY;

-- 24. Policies for debriefings
DROP POLICY IF EXISTS "Users can view their own debriefings" ON public.debriefings;
CREATE POLICY "Users can view their own debriefings" ON public.debriefings
    FOR SELECT USING (
        auth.uid() IN (
            SELECT user_id FROM public.reservations WHERE id = debriefings.reservation_id
        ) OR 
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('instructor', 'admin'))
    );

DROP POLICY IF EXISTS "Instructors and Admins can insert/update debriefings" ON public.debriefings;
CREATE POLICY "Instructors and Admins can insert/update debriefings" ON public.debriefings
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('instructor', 'admin'))
    );

-- 39. course_progress tables
CREATE TABLE IF NOT EXISTS public.course_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    course_level TEXT NOT NULL, -- 입문/초급/중급/고급
    status TEXT NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress', 'completed', 'dropped')),
    theory_completed BOOLEAN DEFAULT false,
    pool_sessions_completed INTEGER DEFAULT 0,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    completed_at TIMESTAMP WITH TIME ZONE,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, course_level)
);

ALTER TABLE public.course_progress ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own progress" ON public.course_progress;
CREATE POLICY "Users can view their own progress" ON public.course_progress
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Instructors and Admins can view all progress" ON public.course_progress;
CREATE POLICY "Instructors and Admins can view all progress" ON public.course_progress
    FOR SELECT USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('instructor', 'admin'))
    );

DROP POLICY IF EXISTS "Instructors and Admins can manage progress" ON public.course_progress;
CREATE POLICY "Instructors and Admins can manage progress" ON public.course_progress
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('instructor', 'admin'))
    );

-- 70. skill_completions 테이블 (스킬 체크리스트)
CREATE TABLE IF NOT EXISTS public.skill_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    course_level TEXT NOT NULL, -- 입문/초급/중급/고급
    skill_type TEXT NOT NULL,   -- static, dynamic, depth, rescue, theory
    is_completed BOOLEAN DEFAULT false,
    completed_at TIMESTAMP WITH TIME ZONE,
    completed_by UUID REFERENCES public.profiles(id), -- 확인한 강사
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, course_level, skill_type)
);

ALTER TABLE public.skill_completions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own skills" ON public.skill_completions;
CREATE POLICY "Users can view their own skills" ON public.skill_completions
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Instructors and Admins can view all skills" ON public.skill_completions;
CREATE POLICY "Instructors and Admins can view all skills" ON public.skill_completions
    FOR SELECT USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('instructor', 'admin'))
    );

DROP POLICY IF EXISTS "Instructors and Admins can manage skills" ON public.skill_completions;
CREATE POLICY "Instructors and Admins can manage skills" ON public.skill_completions
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('instructor', 'admin'))
    );

-- 100. certificates 테이블 (자격증 발급)
-- 기존 certification_requests와 별도로, '발급된 자격증'을 관리 (설계서 v2 반영)
CREATE TABLE IF NOT EXISTS public.certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    certificate_level TEXT NOT NULL, -- 입문/초급/중급/고급
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'issued', 'rejected')),
    certificate_number VARCHAR,      -- 자격증 번호
    applied_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    approved_at TIMESTAMP WITH TIME ZONE,
    issued_at TIMESTAMP WITH TIME ZONE,
    credit_paid INTEGER DEFAULT 0,
    rejection_reason TEXT,
    admin_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own certificates" ON public.certificates;
CREATE POLICY "Users can view their own certificates" ON public.certificates
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert certificate requests" ON public.certificates;
CREATE POLICY "Users can insert certificate requests" ON public.certificates
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Instructors and Admins can view all certificates" ON public.certificates;
CREATE POLICY "Instructors and Admins can view all certificates" ON public.certificates
    FOR SELECT USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('instructor', 'admin'))
    );

DROP POLICY IF EXISTS "Instructors and Admins can manage certificates" ON public.certificates;
CREATE POLICY "Instructors and Admins can manage certificates" ON public.certificates
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('instructor', 'admin'))
    );

-- 트리거 함수: updated_at 자동 갱신
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 트리거 적용
DROP TRIGGER IF EXISTS update_debriefings_updated_at ON public.debriefings;
CREATE TRIGGER update_debriefings_updated_at BEFORE UPDATE ON public.debriefings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_course_progress_updated_at ON public.course_progress;
CREATE TRIGGER update_course_progress_updated_at BEFORE UPDATE ON public.course_progress FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_skill_completions_updated_at ON public.skill_completions;
CREATE TRIGGER update_skill_completions_updated_at BEFORE UPDATE ON public.skill_completions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_certificates_updated_at ON public.certificates;
CREATE TRIGGER update_certificates_updated_at BEFORE UPDATE ON public.certificates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
